### ISSUE TITLE
No support for signing messages with walletConnectProvider

### ISSUE THREAD

**Issue by ethwork** [multiversx/mx-sdk-js-core#105]
Currently only the extension and ledger providers support signing messages. Will support for signing messages with the Maiar app be added? Without it developing dapps that use a backend authentication via signatures is more or less impossible for mobile users.

**Comment by michavie** [comment]
you can add an optional `token` query param to the uri that is returned by the providers login() method (used for generating the QR code).
once resolved it allows you to retrieve a signature via: https://github.com/ElrondNetwork/elrond-sdk-erdjs/blob/f0368251ff9a7e263214d1d88e8243c8ec0f8946/src/dapp/walletConnectProvider.ts#L116

**Comment by ethwork** [comment]
> you can add an optional arbitrary `token` query param to the uri that is returned by the providers login() method (used for generating the QR code). once resolved it allows you to retrieve a signature via:
> 
> https://github.com/ElrondNetwork/elrond-sdk-erdjs/blob/f0368251ff9a7e263214d1d88e8243c8ec0f8946/src/dapp/walletConnectProvider.ts#L116

That looks very promising, thank you! How do I extract the token from the signature afterwards though?

**Comment by michavie** [comment]
since you provide/generate the token on the backend side, you have all the information available to verify signatures coming from the client.
basically: generate random token & store for current 'session' -> let client sign it -> send signature + address to backend for verification -> use sig + address + saved token to verify

**Comment by ethwork** [comment]
> since you provide/generate the token on the backend side, you have all the information available to verify signatures coming from the client. basically: generate random token & store for current 'session' -> let client sign it -> send signature + address to backend for verification -> use sig + address + saved token to verify

Thanks for the help so far. I still have trouble verifying the signature in my backend. This is what I've tried:

```javascript
import { Address, UserVerifier, SignableMessage } from "@elrondnetwork/erdjs";
import { Signature } from "@elrondnetwork/erdjs/out/signature";

const address = new Address("erd1......");

const token = "exampleToken"; // this is passed to the login function
const signature = new Signature("574b..."); // the signature generated in the login flow

const verifier = UserVerifier.fromAddress(address);

const validSignature = verifier.verify(
  new SignableMessage({ address, signature, message: Buffer.from(token) })
);

console.log(validSignature); // FALSE
```

Any tips?

**Comment by michavie** [comment]
@ethwork 

the dapp providers sign a message in the format `<address><token>{} `

try ```Buffer.from(`${address}${token}{}`)```

**Comment by ethwork** [comment]
> @ethwork
> 
> the dapp providers sign a message in the format `<address><token>{} `
> 
> try `` Buffer.from(`${address}${token}{}`) ``

Works like a charm. Thank you so much for the help @michavie !

**Comment by schmitzt3** [comment]
@michavie Hello! Do you know what happened to the `UserVerifier` in the latest version of erdjs? (at this time @elrondnetwork/erdjs@^10.2.5)

**Comment by schmitzt3** [comment]
@michavie Classic - thank you!

**Comment by andreibancioiu** [comment]
The issue will be closed now. For future reference:
 - https://github.com/multiversx/mx-sdk-js-native-auth-server
 - https://github.com/multiversx/mx-sdk-js-native-auth-client
 - https://docs.multiversx.com/sdk-and-tools/sdk-js/sdk-js-signing-providers#verifying-the-signature-of-a-login-token
 - https://github.com/multiversx/mx-sdk-js-examples/blob/main/signing-providers
