### ISSUE TITLE
Feature request: signMessage implemented for all login methods.

### ISSUE THREAD

**Issue by dan-merlea** [multiversx/mx-sdk-js-core#134]
I'm developing a platform highly dependent on signing a message, so I can authenticate server requests.

export interface IDappProvider {
 ....
    signMessage(transaction: SignableMessage, options?: {
        callbackUrl?: string;
    }): Promise<SignableMessage>;
....
}

Is there any timeline for this method to be implemented in other login methods apart from the Extension?
At least Maiar App, that's the most used one so far.

Thanksss!

**Comment by hanahdev** [comment]
> I'm developing a platform highly dependent on signing a message, so I can authenticate server requests.
> 
> export interface IDappProvider { .... signMessage(transaction: SignableMessage, options?: { callbackUrl?: string; }): Promise; .... }
> 
> Is there any timeline for this method to be implemented in other login methods apart from the Extension? At least Maiar App, that's the most used one so far.
> 
> Thanksss!

we are so sorry for the late reply kindly contact there live chat support on whatsapp -  +19546679281

**Comment by andreibancioiu** [comment]
All signing providers now support `signMessage`, as well - including Wallet Connect provider:

https://github.com/multiversx/mx-sdk-js-wallet-connect-provider/blob/main/src/walletConnectV2Provider.ts
