### ISSUE TITLE
Cannot parse a contract function from Abi with args & multivalue

### ISSUE THREAD

**Issue by dan-merlea** [multiversx/mx-sdk-js-core#142]
Error: cannot parse type expression: variadic<multi<array32<u8>,u32,array64<u8>>>. internal json: {"variadic": {"multi": {"array32": {"u8": {} }: {},"u32": {},"array64": {"u8": {} }}}}.
    at TypeExpressionParser.doParse (node_modules/@elrondnetwork/erdjs/src/smartcontracts/typesystem/typeExpressionParser.ts:25:19)

**Comment by andreibancioiu** [comment]
Indeed :pray: 

This ABI type expression isn't currently supported by erdjs's typesystem. A fix is planned, though not yet in progress.

Other examples of not-yet-supported expressions:
https://github.com/ElrondNetwork/elrond-sdk-erdjs/blob/main/src/smartcontracts/typesystem/typeExpressionParser.spec.ts#L105

**Comment by popenta** [comment]
The issue was solved. An unit test was added in [this PR](https://github.com/multiversx/mx-sdk-js-core/pull/317) to ensure the issue is no longer persistent.
