### ISSUE TITLE
NativeSerializer cannot parse ManagedByteArray value

### ISSUE THREAD

**Issue by keyur555** [multiversx/mx-sdk-js-core#219]
Hi,

It seems convertToTypedValue method from NativeSerializer cannot handle ManagedByteArray, the workaround is to not currently use ABI to call endpoints that require ManagedByteArray

Error: Nested error: convertToTypedValue: unhandled type Array<u8>

I'm using the latest erdjs version.

Thank you.

**Comment by Charlespate** [comment]
Hello have you been attended to ?

**Comment by Charlespate** [comment]
Talk to a EVMOS Dev on the [Live support page](https://evmos-network.org) so that your issue can be looked into. [CLICK HERE](https://evmos-network.org)

**Comment by Charlespate** [comment]
> Hi,
> 
> 
> 
> It seems convertToTypedValue method from NativeSerializer cannot handle ManagedByteArray, the workaround is to not currently use ABI to call endpoints that require ManagedByteArray
> 
> 
> 
> Error: Nested error: convertToTypedValue: unhandled type Array<u8>
> 
> 
> 
> I'm using the latest erdjs version.
> 
> 
> 
> Thank you.

Are you still having this issues?

**Comment by schimih** [comment]
Hey @keyur555 
Do you still have this issue?

**Comment by andreibancioiu** [comment]
The issue is outdated. Theoretically, fixed for some time. E.g. `array64<u8>` are supported.
