### ISSUE TITLE
Add a local wallet provider

### ISSUE THREAD

**Issue by lcswillems** [multiversx/mx-sdk-js-core#232]
A provider that loads a local wallet would be a nice improvement. It would be particularly useful for scripts that deploy smart contracts.

Another use case would be to make a web wallet. People could add their keystore in a website and use it to sign transactions directly in the app.

**Comment by MWFIAE** [comment]
Bit of a late follow up, but I think everything you need is already there :) 
It can handle pems, mnemonics and keystore files and provides a UserSigner that just takes a private key :)
https://github.com/multiversx/mx-sdk-js-wallet

Though it is not a good idea to directly handle users private keys in a dapp, as that will be a huge security risk :)

**Comment by andreibancioiu** [comment]
Support exists for some time, indeed:
 - https://docs.multiversx.com/sdk-and-tools/sdk-js/sdk-js-cookbook/#contract-deployments
 - https://docs.multiversx.com/sdk-and-tools/sdk-js/sdk-js-cookbook/#signing-objects

Issue will be closed. Thank you :pray:
