### ISSUE TITLE
Handling Transaction value >= 1e21

### ISSUE THREAD

**Issue by newtmex** [multiversx/mx-sdk-js-core#254]
The [`toPlainObject`](https://github.com/multiversx/mx-sdk-js-core/blob/e13ad27b48994d1fe72e64b1bce4b81f07e23ba3/src/transaction.ts#L221) and [`fromPlainObject`](https://github.com/multiversx/mx-sdk-js-core/blob/e13ad27b48994d1fe72e64b1bce4b81f07e23ba3/src/transaction.ts#L242) methods of the [`Transaction`](https://github.com/multiversx/mx-sdk-js-core/blob/e13ad27b48994d1fe72e64b1bce4b81f07e23ba3/src/transaction.ts#L23) class in some way calls the `toString()` method of bignumber.js which returns the exponential value for numbers >= 1e21.

This causes invalid signature issues when signing transactions.

**Comment by andreibancioiu** [comment]
@newtmex, thank you for the report - and for the PR :pray: 

On this purpose, we'll most probably have a new version tomorrow.
