### ISSUE TITLE
BooleanValue is always encoded as false

### ISSUE THREAD

**Issue by gfusee** [multiversx/mx-sdk-js-core#258]
Here is a reproductible example : 

```ts
const booleanString = "true"
const value = NativeSerializer.nativeToTypedValues(
    [booleanString],
    new EndpointDefinition(
        "test",
        [
            new EndpointParameterDefinition("test", "test", new BooleanType())
        ],
        [],
        new EndpointModifiers("mutable", [])
    )
)[0]
const codec = new BinaryCodec()
const encodedTopLevel = codec.encodeTopLevel(value)
const encodedNested = codec.encodeNested(value)
console.log({
    encodedTopLevel: encodedTopLevel.toString("hex"),
    encodedNested: encodedNested.toString("hex")
})
```

And what is logged : 

`{ encodedTopLevel: '', encodedNested: '00' }`

The result is the same if I replace "true" by "1"

I'm using @multiversx/sdk-core: ^11.3.0

**Comment by gfusee** [comment]
It may not be a bug since true or 1 instead of "true" or "1" is working, but this leads to confusion to consider "true" as false

**Comment by danielailie** [comment]
Hello, we added a converter at the nativeSerializer to validate also string and number for bool values. 
Now "true" and 1 will also be consider as true value
This is the [Pr](https://github.com/multiversx/mx-sdk-js-core/pull/467) with the updates 
And we also publish a minor release that will hold this updates. The release is [this](https://www.npmjs.com/package/@multiversx/sdk-core/v/13.3.0)

Thank you for pointing it out. Let us know is you still have issues with this one
