### ISSUE TITLE
In some cases, consider using non-fixed versions for dependencies

### ISSUE THREAD

**Issue by andreibancioiu** [multiversx/mx-sdk-js-core#290]
- E.g. for `BigNumber.js`. Also, try not to receive (nor return?) `BigNumber` instances in functions - receive `BigNumber.Value` interface instead. Try to not break the behavior of `instanceof BigNumber`.

**Comment by CiprianDraghici** [comment]
I'd use ~ for some packages. It's a more controlled way to avoid breakings. For minor versions upgrades we should take care of them and when a new version of the `sdk-core` is released then it will contains all the dependencies upgraded and tested.

**Comment by danielailie** [comment]
Axios and BigNumber are already as peer dependencies with ^ on sdk-core 
We also added axios as a peer dependency on network-providers with this [pr ](https://github.com/multiversx/mx-sdk-js-network-providers/pull/65)
