### ISSUE TITLE
Support to deserialize signed transactions

### ISSUE THREAD

**Issue by yagop** [multiversx/mx-sdk-js-core#296]
I want to deserialize a signed transaction hex into a Transaction object, but seems implementation is missing.

Is there any way to achieve this?

**Comment by schimih** [comment]
Hey @yagop ,

Can you provide more information? Maybe add an example of what you want to achieve?

**Comment by yagop** [comment]
Hey @schimih sure, Imagine we have the tx hash (and the signature) but we need the Transaction object to be able to broadcast the tx.

```ts
import {
    Account,
    Address,
    TokenPayment,
    Transaction,
    TransactionVersion,
} from '@multiversx/sdk-core'
import { UserSecretKey, UserSigner } from '@multiversx/sdk-wallet'

const account = new Account(new Address(...));
const signer = new UserSigner(UserSecretKey.fromPem(...));

const tx = new Transaction({
    // ...
});
const serializedTransaction = tx.serializeForSigning();
const signature = await signer.sign(serializedTransaction);
```

```ts
// In other part of the code
function broadcastTx(txhash: string, signature: string) {
  
}
```

The [sendTransaction(tx: ITransaction)](https://github.com/multiversx/mx-sdk-js-network-providers/blob/7bb49e6be570e581a92154aabbb63fb8db82eac4/src/proxyNetworkProvider.ts#L115) method requires a `ITransaction` interface.

**Comment by yagop** [comment]
Bump 😅

**Comment by andreibancioiu** [comment]
Hello @yagop,

The `transaction hash` is a 32-byte sequence. `Signature` is a 64-byte sequence. Neither can be used to recover the transaction object (theoretically & practically impossible).

Perhaps there's the confusion that `txHash` and `signature` are serialized representations of a transaction? **They are not**. They are artifacts obtained through content hashing / computing digital signatures.

Simply use the same `tx` object to broadcast the transaction:

```
// Your code
const tx = new Transaction({
    // ...
});
const serializedTransaction = tx.serializeForSigning();
const signature = await signer.sign(serializedTransaction);

// New code
tx.applySignature(signature);
await networkProvider.sendTransaction(tx);
```

`tx` (as a `Transaction`) follows the `ITransaction` interface (they are compatible).

Also, make sure to have a look on the Cookbook:

https://docs.multiversx.com/sdk-and-tools/sdk-js/sdk-js-cookbook/
