### ISSUE TITLE
Add support for `counted-variadic` type in ABI parsing

### ISSUE THREAD

**Issue by raress96** [multiversx/mx-sdk-js-core#316]
The Rust SDK supports the MultiValueManagedVecCounted type:
https://github.com/multiversx/mx-sdk-rs/blob/master/framework/base/src/types/managed/multi_value/multi_value_managed_vec_counted.rs

Which in the ABI appears like a `counted-variadic` (eg: `counted-variadic<BigUint>`).

If this type appears in the ABI file, the SDK JS Core can no longer parse that ABI.

The type is similar to the `variadic` type, just that it has a U32 (length of the vec) before the elements. It would be nice if support for this could be implemented.

**Comment by andreibancioiu** [comment]
Fixed in https://github.com/multiversx/mx-sdk-js-core/releases/tag/v12.8.0.
